// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://miiybtxnnxlimmiyfauy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1paXlidHhubnhsaW1taXlmYXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4MTkzNjEsImV4cCI6MjA5MTM5NTM2MX0.j3sCoqF63PJymzk9SOa1zPK_hDbrPoq9Dg6agobFSuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});